name: My First Cloud Automation

on:
  push:
    branches: [ "master" ]

jobs:
  run-test-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Print Welcome Message
        run: echo "The GitHub cloud machine is working perfectly!"
