on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Say Hello
        uses: ./template
        with:
          who-to-greet: 'Mona'

