#nojrs
name: manual working

on:
  push:
    branch: [master]
    

  workflow_dispatch:
    inputs:
      name:
        description: 'name for the yml'
        required: true
        type: string
      greeting:
        description: 'type the greeting'
        required: true
        type: string
      data:
        description: 'Base64 encoded content of a file'
        required: false
        type: string




jobs:
  hello: 
    runs-on: ubuntu-latest
    steps:
      - name: helloing
        run: echo "hi , ${{inputs.name}}"
      - name: greeting
        run: echo "${{inputs.greetig}} , ${{inputs.name}}, ${{inputs.data}}, trying to run this code with manual approach help meeeeeee"
      - name: Display File Content
        run: |
          echo "Contents of the file:"
          cat ./decoded_file.txt

    