#nodsr
name: helo ji
on: 
  push:
    branches: [master]
  pull_request_target: 
    branches: [master]

  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "stating"
        run: echo "hello ji"
      - name: "newing"
        run: echo "hanji"
  dance:
    runs-on: ubuntu-22.04
    steps:
      - name: "This is kathak"
        run: echo "india 's heritage"
      - name: "This is Bharatnatyam "
        run: echo "dancing bharat "              
      - name: secret key existence
        env:
          mypassword: "${{ secrets.MY_TEST_PASSWORD }}"
        run: echo "$mypassword"

