name: helo ji
on: 
  push:
    branches:  [master]
  pull_request_target: 
    branches:  [master]

  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "stating"
        run: echo "hello ji"
      - name:  "newing"
        run: echo "hanji"
