#nodsr
name: helo ji
on: 
  schedule:
    - cron: '*/1 * * * *' 

  push:
    branches: [master]
  pull_request_target: 
    branches: [master]
  issues:

jobs:
  hello:
    runs-on: ubuntu-latest
    needs: dance
    steps:
      - name: "stating"
        run: echo "hello ji"
      - name: "newing"
        run: echo "hanji"
  dance:
    needs: byebye
    runs-on: ubuntu-22.04
    steps:
      - name: "This is kathak"
        run: echo "india 's heritage"
      - name: "This is Bharatnatyam "
        run: echo "dancing bharat "              
      - name: secret key existence
        env:
          mypassword: "${{ secrets.MY_TEST_PASSWORD }}"
        run: echo "$mypassword"
  byebye:   
    runs-on: ubuntu-22.04
    steps:
      - name: "This is kathak"
        run: echo "india 's heritage"
      - name: "This is Bharatnatyam "
        run: echo "dancing bharat "              
      - name: secret key existence
        env:
          mypassword: "${{ secrets.MY_TEST_PASSWORD }}"
        run: echo "$mypassword"

