name: Repository Dispatch Demo

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  webhook-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print Event
        run: |
          echo "Workflow triggered successfully!"
          echo "Event Name: $GITHUB_EVENT_NAME"

      - name: Print Payload
        run: |
          echo "Name: ${{ github.event.client_payload.name }}"
          echo "Course: ${{ github.event.client_payload.course }}"